import java.awt.Color;
import javax.swing.*;
import java.util.*;

public class AddChangeEmployee_jFrame extends javax.swing.JFrame {
    public MyHashTable employeeTable;
    public javax.swing.JButton jSearchButton;
    public javax.swing.JFormattedTextField[] FTEFieldArray;
    public javax.swing.JFormattedTextField[] PTEFieldArray;
    public Map<javax.swing.JFormattedTextField, String> textFieldType;
    public EmployeeInfo selectedEmployee;
    
    public AddChangeEmployee_jFrame(MyHashTable employeeTable, javax.swing.JButton jSearchButton) {
        initComponents();
        this.employeeTable = employeeTable;
        this.jSearchButton = jSearchButton;
        this.FTEFieldArray = new JFormattedTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jDeductRateTextField, jSalaryTextField};
        this.PTEFieldArray = new JFormattedTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jDeductRateTextField, jHourlyWageTextField, jHoursPerWeekTextField, jWeeksPerYearTextField};
        this.textFieldType = Map.of(jEmployeeNumberTextField, "0", jFirstNameTextField,"", jLastNameTextField, "", jDeductRateTextField, "0%", jSalaryTextField, "0", jHourlyWageTextField, "0", jHoursPerWeekTextField, "0", jWeeksPerYearTextField, "0");
        clearText(FTEFieldArray);
        clearText(PTEFieldArray);
        jAddChangeButton.setText("Add");
        jResponseLabel.setText(""); 
        jFTERadioButton.doClick();  
        pack();
    }
    
    public AddChangeEmployee_jFrame(MyHashTable employeeTable, javax.swing.JButton jSearchButton, EmployeeInfo selectedEmployee) {
        this(employeeTable, jSearchButton);
        this.selectedEmployee = selectedEmployee;
        this.setTitle("Change Employee #" + Integer.toString(selectedEmployee.employeeNumber));
        jAddChangeButton.setText("Change");
        jEmployeeNumberTextField.setValue(selectedEmployee.employeeNumber);
        jFirstNameTextField.setText(selectedEmployee.firstName);
        jLastNameTextField.setText(selectedEmployee.lastName);
        jDeductRateTextField.setValue(selectedEmployee.deductRate);
        if (selectedEmployee instanceof FTE){
            jFTERadioButton.doClick();
            jSalaryTextField.setValue(((FTE)selectedEmployee).yearlySalary);
        }
        else {
            jPTERadioButton.doClick();
            jHourlyWageTextField.setValue(((PTE)selectedEmployee).hourlyWage);
            jHoursPerWeekTextField.setValue(((PTE)selectedEmployee).hoursPerWeek);
            jWeeksPerYearTextField.setValue(((PTE)selectedEmployee).weeksPerYear);
        }
    }
    
    public void clearText(javax.swing.JFormattedTextField[] array){
        for (javax.swing.JFormattedTextField textField: array){
            textField.setText(textFieldType.get(textField));
        }
    }
    
    public void clearColor(javax.swing.JFormattedTextField[] array){
        for (javax.swing.JFormattedTextField textField: array){
            textField.setBackground(Color.white);
        }
    }
    
    public Object[] getField(javax.swing.JFormattedTextField[] array){
        Object[] output = new Object[array.length];
        for (int i = 0; i < array.length; i++){
            if (array[i].getValue() == null){
                System.out.println(array[i].getText() + " a");
                output[i] = (Object)array[i].getText();
            }
            else {
                System.out.println(array[i].getValue());
                output[i] = (Object)array[i].getValue();
            }
        }
        return output;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jAddChangeButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();
        jResponseLabel = new javax.swing.JLabel();
        jFTERadioButton = new javax.swing.JRadioButton();
        jPTERadioButton = new javax.swing.JRadioButton();
        jMainPanel = new javax.swing.JPanel();
        jEmployeeNumberLabel = new javax.swing.JLabel();
        jFirstNameLabel = new javax.swing.JLabel();
        jLastNameLabel = new javax.swing.JLabel();
        jEmployeeNumberTextField = new javax.swing.JFormattedTextField();
        jFirstNameTextField = new javax.swing.JFormattedTextField();
        jLastNameTextField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jDeductRateTextField = new javax.swing.JFormattedTextField();
        jPTEPanel = new javax.swing.JPanel();
        jHourlyWageLabel = new javax.swing.JLabel();
        jHoursPerWeekLabel = new javax.swing.JLabel();
        jWeeksPerYearLabel = new javax.swing.JLabel();
        jHourlyWageTextField = new javax.swing.JFormattedTextField();
        jHoursPerWeekTextField = new javax.swing.JFormattedTextField();
        jWeeksPerYearTextField = new javax.swing.JFormattedTextField();
        jFTEPanel = new javax.swing.JPanel();
        jSalaryTextField = new javax.swing.JFormattedTextField();
        jSalaryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");
        setMinimumSize(new java.awt.Dimension(0, 260));
        setResizable(false);

        jAddChangeButton.setText("A/C");
        jAddChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddChangeButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Exit");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jResponseLabel.setText(" ");

        buttonGroup1.add(jFTERadioButton);
        jFTERadioButton.setText("Full time");
        jFTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedFTERadioButton(evt);
            }
        });

        buttonGroup1.add(jPTERadioButton);
        jPTERadioButton.setText("Part time");
        jPTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedPTERadioButton(evt);
            }
        });

        jEmployeeNumberLabel.setText("Employee Number");
        jEmployeeNumberLabel.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        jEmployeeNumberLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jFirstNameLabel.setText("First Name");
        jFirstNameLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jLastNameLabel.setText("Last Name");
        jLastNameLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        javax.swing.text.NumberFormatter employeeNumberFormatter = new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"));
        employeeNumberFormatter.setAllowsInvalid(false);
        employeeNumberFormatter.setCommitsOnValidEdit(true);
        employeeNumberFormatter.setOverwriteMode(false);
        employeeNumberFormatter.setMinimum(0);
        employeeNumberFormatter.setMaximum(999999999);
        jEmployeeNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(employeeNumberFormatter));
        jEmployeeNumberTextField.setText("0");
        jEmployeeNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIntegerTextFieldKeyPressed(evt);
            }
        });

        jLabel1.setText("Deduct Rate");

        javax.swing.text.NumberFormatter deductRateFormatter = new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0%"));
        deductRateFormatter.setAllowsInvalid(false);
        deductRateFormatter.setCommitsOnValidEdit(true);
        deductRateFormatter.setOverwriteMode(false);
        deductRateFormatter.setMinimum(0.0);
        deductRateFormatter.setMaximum(1.0);
        jDeductRateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(deductRateFormatter));
        jDeductRateTextField.setText("0%");
        jDeductRateTextField.setToolTipText("");
        jDeductRateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPercentTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jEmployeeNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jFirstNameTextField)
                        .addComponent(jLastNameTextField))
                    .addComponent(jDeductRateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jDeductRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jHourlyWageLabel.setText("Hourly Wage");
        jHourlyWageLabel.setMaximumSize(new java.awt.Dimension(57, 16));
        jHourlyWageLabel.setMinimumSize(new java.awt.Dimension(57, 16));

        jHoursPerWeekLabel.setText("Hours per week");
        jHoursPerWeekLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jWeeksPerYearLabel.setText("Weeks per year");
        jWeeksPerYearLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        javax.swing.text.NumberFormatter hourlyWageFormatter = new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance());
        hourlyWageFormatter.setAllowsInvalid(false);
        hourlyWageFormatter.setCommitsOnValidEdit(true);
        hourlyWageFormatter.setOverwriteMode(false);
        hourlyWageFormatter.setMinimum(0.0);
        hourlyWageFormatter.setMaximum(999999999.0);
        jHourlyWageTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(hourlyWageFormatter));
        jHourlyWageTextField.setText("$0.00");
        jHourlyWageTextField.setToolTipText("");
        jHourlyWageTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDoubleTextFieldPropertyChange(evt);
            }
        });

        javax.swing.text.NumberFormatter hoursPerWeekFormatter = new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"));
        hoursPerWeekFormatter.setAllowsInvalid(false);
        hoursPerWeekFormatter.setCommitsOnValidEdit(true);
        hoursPerWeekFormatter.setOverwriteMode(false);
        hoursPerWeekFormatter.setMinimum(0);
        hoursPerWeekFormatter.setMaximum(168);
        jHoursPerWeekTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(hoursPerWeekFormatter));
        jHoursPerWeekTextField.setText("0");
        jHoursPerWeekTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIntegerTextFieldKeyPressed(evt);
            }
        });

        javax.swing.text.NumberFormatter weeksPerYearFormatter = new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"));
        weeksPerYearFormatter.setAllowsInvalid(false);
        weeksPerYearFormatter.setCommitsOnValidEdit(true);
        weeksPerYearFormatter.setOverwriteMode(false);
        weeksPerYearFormatter.setMinimum(0);
        weeksPerYearFormatter.setMaximum(52);
        jWeeksPerYearTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(weeksPerYearFormatter));
        jWeeksPerYearTextField.setText("0");
        jWeeksPerYearTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIntegerTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPTEPanelLayout = new javax.swing.GroupLayout(jPTEPanel);
        jPTEPanel.setLayout(jPTEPanelLayout);
        jPTEPanelLayout.setHorizontalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTEPanelLayout.createSequentialGroup()
                        .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTEPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWeeksPerYearTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPTEPanelLayout.setVerticalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.text.NumberFormatter salaryFormatter = new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance());
        salaryFormatter.setAllowsInvalid(false);
        salaryFormatter.setCommitsOnValidEdit(true);
        salaryFormatter.setOverwriteMode(false);
        salaryFormatter.setMinimum(0.0);
        salaryFormatter.setMaximum(999999999.0);
        jSalaryTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(salaryFormatter));
        jSalaryTextField.setText("$0.00");
        jSalaryTextField.setToolTipText("");
        jSalaryTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDoubleTextFieldPropertyChange(evt);
            }
        });

        jSalaryLabel.setText("Salary");
        jSalaryLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        javax.swing.GroupLayout jFTEPanelLayout = new javax.swing.GroupLayout(jFTEPanel);
        jFTEPanel.setLayout(jFTEPanelLayout);
        jFTEPanelLayout.setHorizontalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFTEPanelLayout.setVerticalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFTEPanelLayout.createSequentialGroup()
                .addGroup(jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPTERadioButton)
                                    .addComponent(jFTERadioButton)))
                            .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAddChangeButton)
                                .addGap(30, 30, 30)
                                .addComponent(jRemoveButton)
                                .addGap(30, 30, 30)
                                .addComponent(jResponseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTERadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPTERadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddChangeButton)
                    .addComponent(jRemoveButton)
                    .addComponent(jResponseLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddChangeButtonActionPerformed
        clearColor(FTEFieldArray);
        clearColor(PTEFieldArray);
        ArrayList<javax.swing.JFormattedTextField> list = new ArrayList();
        if (employeeTable.retrieve((int)jEmployeeNumberTextField.getValue()) != null){
            if (jAddChangeButton.getText().equals("Add")){
                list.add(jEmployeeNumberTextField);
            }
            else if ((int)jEmployeeNumberTextField.getValue() != selectedEmployee.employeeNumber){
                list.add(jEmployeeNumberTextField);
            }
        }
        if (jFirstNameTextField.getText().equals("")){
            list.add(jFirstNameTextField);
        }
        if (jLastNameTextField.getText().equals("")){
            list.add(jLastNameTextField);
        }
        if (list.isEmpty()){
            if (jFTERadioButton.isSelected()){
                FTE item = new FTE(getField(FTEFieldArray));
                employeeTable.add(item);
            }
            else {
                PTE item = new PTE(getField(PTEFieldArray));
                employeeTable.add(item);  
            }
            if (jAddChangeButton.getText().equals("Add")){
                selectedEmployee = null;
                jResponseLabel.setText("Employee Added");
                clearText(FTEFieldArray);
                clearText(PTEFieldArray);
            }
            else{
                jResponseLabel.setText("Employee Updated"); 
                employeeTable.remove(selectedEmployee.employeeNumber);
                selectedEmployee = employeeTable.retrieve((int)jEmployeeNumberTextField.getValue());
            }
            jSearchButton.doClick();
        }
        else {
            for (javax.swing.JFormattedTextField i : list){
                i.setBackground(new Color(255, 150, 150));
                jResponseLabel.setText("Invalid Field");
            }
        }
    }//GEN-LAST:event_jAddChangeButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void clickedFTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedFTERadioButton
        jPTEPanel.setVisible(false);
        jFTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedFTERadioButton

    private void clickedPTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedPTERadioButton
        jFTEPanel.setVisible(false);
        jPTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedPTERadioButton

    private void jDoubleTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDoubleTextFieldPropertyChange
        if (evt.getPropertyName().equals("value")){
            javax.swing.JFormattedTextField field = (javax.swing.JFormattedTextField)evt.getSource();
            if (evt.getOldValue().equals(0.0) && (double)evt.getNewValue() % 1 == 0.0){
                field.setText(evt.getNewValue().toString().replace("0", ""));
            }
            else if ((double)evt.getNewValue()/100 == (double)evt.getOldValue()){
                String t = evt.getOldValue().toString();
                field.setText(t.substring(0, t.indexOf(".") - 1) + t.substring(t.indexOf(".")));
            }
            else {
                return;
            }
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    field.setCaretPosition(field.getText().length() - 3);
                }
            });
            
        }
    }//GEN-LAST:event_jDoubleTextFieldPropertyChange
    private void jIntegerTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIntegerTextFieldKeyPressed
        javax.swing.JFormattedTextField field = (javax.swing.JFormattedTextField)evt.getSource();
        if (field.getText().length() == 1) {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE && field.getCaretPosition() == 1 && !field.getText().equals("0")){
                evt.consume();
                field.setText("0");
            }
            else if (field.getText().equals("0") && "0123456789".contains(Character.toString(evt.getKeyChar()))){
                field.setText("0");
            }
        }
    }//GEN-LAST:event_jIntegerTextFieldKeyPressed

    private void jPercentTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPercentTextFieldKeyPressed
        javax.swing.JFormattedTextField field = (javax.swing.JFormattedTextField)evt.getSource();
        if (field.getText().length() == 2 && evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE && field.getCaretPosition() == 1 && !field.getText().equals("0%")) {
            evt.consume();
            field.setText("0%");  
        }
        else if ((field.getCaretPosition() == field.getText().length() - 1 || field.getText().equals("0%")) && "0123456789".contains(Character.toString(evt.getKeyChar()))){
            field.setText(field.getText().replace("%", evt.getKeyChar() + "%"));
        } 
    }//GEN-LAST:event_jPercentTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddChangeButton;
    private javax.swing.JFormattedTextField jDeductRateTextField;
    private javax.swing.JLabel jEmployeeNumberLabel;
    private javax.swing.JFormattedTextField jEmployeeNumberTextField;
    private javax.swing.JPanel jFTEPanel;
    private javax.swing.JRadioButton jFTERadioButton;
    private javax.swing.JLabel jFirstNameLabel;
    private javax.swing.JFormattedTextField jFirstNameTextField;
    private javax.swing.JLabel jHourlyWageLabel;
    private javax.swing.JFormattedTextField jHourlyWageTextField;
    private javax.swing.JLabel jHoursPerWeekLabel;
    private javax.swing.JFormattedTextField jHoursPerWeekTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JFormattedTextField jLastNameTextField;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jPTEPanel;
    private javax.swing.JRadioButton jPTERadioButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JLabel jResponseLabel;
    private javax.swing.JLabel jSalaryLabel;
    private javax.swing.JFormattedTextField jSalaryTextField;
    private javax.swing.JLabel jWeeksPerYearLabel;
    private javax.swing.JFormattedTextField jWeeksPerYearTextField;
    // End of variables declaration//GEN-END:variables
}
