import javax.swing.*;
import java.util.*;

public class AddNewEmployee_jFrame extends javax.swing.JFrame {
    public MyHashTable employeeTable;  // This contains the ref value for theHT of MainJFrame.
    public javax.swing.JTextField[] FTEFieldArray;
    public javax.swing.JTextField[] PTEFieldArray;
    public Map<javax.swing.JTextField, String> textFieldType;
    
    public AddNewEmployee_jFrame(MyHashTable employeeTable) {
        initComponents();
        this.employeeTable = employeeTable;
        this.FTEFieldArray = new JTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jSalaryTextField};
        this.PTEFieldArray = new JTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jHourlyWageTextField, jHoursPerWeekTextField, jWeeksPerYearTextField};
        this.textFieldType = Map.of(jEmployeeNumberTextField, "0", jFirstNameTextField,"", jLastNameTextField, "", jSalaryTextField, "2.00", jHourlyWageTextField, "$0.00", jHoursPerWeekTextField, "0", jWeeksPerYearTextField, "0");
        clearField(FTEFieldArray);
        clearField(PTEFieldArray);
        jResponseLabel.setVisible(false); // Hide the Added new employee message
        jPTERadioButton.doClick();  
        pack();
    }
    
    public void clearField(javax.swing.JTextField[] array){
        for (javax.swing.JTextField textField: array){
            textField.setText(textFieldType.get(textField));
        }
    }
    
    public String[] getField(javax.swing.JTextField[] array){
        String[] output = new String[array.length];
        for (int i = 0; i < array.length; i++){
            output[i] = array[i].getText();
        }
        return output;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jAddButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();
        jResponseLabel = new javax.swing.JLabel();
        jFTERadioButton = new javax.swing.JRadioButton();
        jPTERadioButton = new javax.swing.JRadioButton();
        jMainPanel = new javax.swing.JPanel();
        jEmployeeNumberLabel = new javax.swing.JLabel();
        jFirstNameLabel = new javax.swing.JLabel();
        jFirstNameTextField = new javax.swing.JTextField();
        jLastNameLabel = new javax.swing.JLabel();
        jLastNameTextField = new javax.swing.JTextField();
        jEmployeeNumberTextField = new javax.swing.JTextField();
        jPTEPanel = new javax.swing.JPanel();
        jHourlyWageLabel = new javax.swing.JLabel();
        jHoursPerWeekLabel = new javax.swing.JLabel();
        jHoursPerWeekTextField = new javax.swing.JTextField();
        jWeeksPerYearLabel = new javax.swing.JLabel();
        jWeeksPerYearTextField = new javax.swing.JTextField();
        jHourlyWageTextField = new javax.swing.JFormattedTextField();
        jFTEPanel = new javax.swing.JPanel();
        jSalaryTextField = new javax.swing.JFormattedTextField();
        jSalaryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 260));
        setResizable(false);

        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Exit");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jResponseLabel.setText("Employee added!");

        buttonGroup1.add(jFTERadioButton);
        jFTERadioButton.setText("Full time");
        jFTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedFTERadioButton(evt);
            }
        });

        buttonGroup1.add(jPTERadioButton);
        jPTERadioButton.setText("Part time");
        jPTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedPTERadioButton(evt);
            }
        });

        jEmployeeNumberLabel.setText("Employee Number");
        jEmployeeNumberLabel.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        jEmployeeNumberLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jFirstNameLabel.setText("First Name");
        jFirstNameLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jFirstNameTextField.setMinimumSize(new java.awt.Dimension(60, 20));

        jLastNameLabel.setText("Last Name");
        jLastNameLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jLastNameTextField.setMinimumSize(new java.awt.Dimension(60, 20));

        jEmployeeNumberTextField.setText("0");

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFirstNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmployeeNumberTextField))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jHourlyWageLabel.setText("Hourly Wage");
        jHourlyWageLabel.setMaximumSize(new java.awt.Dimension(57, 16));
        jHourlyWageLabel.setMinimumSize(new java.awt.Dimension(57, 16));

        jHoursPerWeekLabel.setText("Hours per week");
        jHoursPerWeekLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jHoursPerWeekTextField.setText("0");

        jWeeksPerYearLabel.setText("Weeks per year");
        jWeeksPerYearLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jWeeksPerYearTextField.setText("0");

        javax.swing.text.NumberFormatter hourlyWageFormatter = new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance());
        hourlyWageFormatter.setAllowsInvalid(false);
        hourlyWageFormatter.setCommitsOnValidEdit(true);
        hourlyWageFormatter.setOverwriteMode(false);
        hourlyWageFormatter.setMinimum(-0.001);
        hourlyWageFormatter.setMaximum(Double.MAX_VALUE);
        jHourlyWageTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(hourlyWageFormatter));
        jHourlyWageTextField.setText("$0.00");
        jHourlyWageTextField.setToolTipText("");
        jHourlyWageTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDoubleTextFieldPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPTEPanelLayout = new javax.swing.GroupLayout(jPTEPanel);
        jPTEPanel.setLayout(jPTEPanelLayout);
        jPTEPanelLayout.setHorizontalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jWeeksPerYearTextField)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPTEPanelLayout.setVerticalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.text.NumberFormatter salaryFormatter = new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance());
        salaryFormatter.setAllowsInvalid(false);
        salaryFormatter.setCommitsOnValidEdit(true);
        salaryFormatter.setOverwriteMode(false);
        salaryFormatter.setMinimum(-0.001);
        salaryFormatter.setMaximum(Double.MAX_VALUE);
        jSalaryTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(salaryFormatter));
        jSalaryTextField.setText("$0.00");
        jSalaryTextField.setToolTipText("");
        jSalaryTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSalaryTextFieldjDoubleTextFieldPropertyChange(evt);
            }
        });

        jSalaryLabel.setText("Salary");
        jSalaryLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        javax.swing.GroupLayout jFTEPanelLayout = new javax.swing.GroupLayout(jFTEPanel);
        jFTEPanel.setLayout(jFTEPanelLayout);
        jFTEPanelLayout.setHorizontalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFTEPanelLayout.setVerticalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFTEPanelLayout.createSequentialGroup()
                .addGroup(jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jAddButton)
                            .addGap(30, 30, 30)
                            .addComponent(jRemoveButton)
                            .addGap(30, 30, 30)
                            .addComponent(jResponseLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPTERadioButton)
                                .addComponent(jFTERadioButton)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTERadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPTERadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jRemoveButton)
                    .addComponent(jResponseLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        if (jFTERadioButton.isSelected()) {
            employeeTable.add(new FTE(getField(FTEFieldArray)));
            clearField(FTEFieldArray);
        }
        else {
            employeeTable.add(new PTE(getField(PTEFieldArray)));
            clearField(PTEFieldArray);  
        }     
        jResponseLabel.setVisible(true); 
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void clickedFTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedFTERadioButton
        jPTEPanel.setVisible(false);
        jFTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedFTERadioButton

    private void clickedPTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedPTERadioButton
        jFTEPanel.setVisible(false);
        jPTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedPTERadioButton

    private void jDoubleTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDoubleTextFieldPropertyChange
        if (evt.getPropertyName().equals("value") && evt.getOldValue().equals(0.0)){
            System.out.println(evt.getNewValue().getClass());
            double x = (double) evt.getNewValue();
        }
    }//GEN-LAST:event_jDoubleTextFieldPropertyChange

    private void jSalaryTextFieldjDoubleTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSalaryTextFieldjDoubleTextFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalaryTextFieldjDoubleTextFieldPropertyChange

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddButton;
    private javax.swing.JLabel jEmployeeNumberLabel;
    private javax.swing.JTextField jEmployeeNumberTextField;
    private javax.swing.JPanel jFTEPanel;
    private javax.swing.JRadioButton jFTERadioButton;
    private javax.swing.JLabel jFirstNameLabel;
    private javax.swing.JTextField jFirstNameTextField;
    private javax.swing.JLabel jHourlyWageLabel;
    private javax.swing.JFormattedTextField jHourlyWageTextField;
    private javax.swing.JLabel jHoursPerWeekLabel;
    private javax.swing.JTextField jHoursPerWeekTextField;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JTextField jLastNameTextField;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jPTEPanel;
    private javax.swing.JRadioButton jPTERadioButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JLabel jResponseLabel;
    private javax.swing.JLabel jSalaryLabel;
    private javax.swing.JFormattedTextField jSalaryTextField;
    private javax.swing.JLabel jWeeksPerYearLabel;
    private javax.swing.JTextField jWeeksPerYearTextField;
    // End of variables declaration//GEN-END:variables
}
