import javax.swing.*;
import java.lang.Math.*;

public class AddNewEmployee_jFrame extends javax.swing.JFrame {
    public MyHashTable employeeTable;  // This contains the ref value for theHT of MainJFrame.
    public javax.swing.JTextField[] FTEFieldArray;
    public javax.swing.JTextField[] PTEFieldArray;
    
    public AddNewEmployee_jFrame(MyHashTable employeeTable) {
        initComponents();
        this.employeeTable = employeeTable;
        this.FTEFieldArray = new JTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jSalaryTextField};
        this.PTEFieldArray = new JTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jHourlyWageTextField, jHoursPerWeekTextField, jWeeksPerYearTextField};
        clearField(FTEFieldArray);
        clearField(PTEFieldArray);
        jResponseLabel.setVisible(false); // Hide the Added new employee message
        jFTERadioButton.doClick();  
        pack();
    }
    
    public void clearField(javax.swing.JTextField[] array){
        for (javax.swing.JTextField textField: array){
            textField.setText("");
        }
    }
    
    public String[] getField(javax.swing.JTextField[] array){
        String[] output = new String[array.length];
        for (int i = 0; i < array.length; i++){
            output[i] = array[i].getText();
        }
        return output;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jAddButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();
        jResponseLabel = new javax.swing.JLabel();
        jFTERadioButton = new javax.swing.JRadioButton();
        jPTERadioButton = new javax.swing.JRadioButton();
        jFTEPanel = new javax.swing.JPanel();
        jSalaryLabel = new javax.swing.JLabel();
        jSalaryTextField = new javax.swing.JFormattedTextField();
        jPTEPanel = new javax.swing.JPanel();
        jHourlyWageLabel = new javax.swing.JLabel();
        jHourlyWageTextField = new javax.swing.JTextField();
        jHoursPerWeekLabel = new javax.swing.JLabel();
        jHoursPerWeekTextField = new javax.swing.JTextField();
        jWeeksPerYearLabel = new javax.swing.JLabel();
        jWeeksPerYearTextField = new javax.swing.JTextField();
        jMainPanel = new javax.swing.JPanel();
        jEmployeeNumberLabel = new javax.swing.JLabel();
        jFirstNameLabel = new javax.swing.JLabel();
        jFirstNameTextField = new javax.swing.JTextField();
        jLastNameLabel = new javax.swing.JLabel();
        jLastNameTextField = new javax.swing.JTextField();
        jEmployeeNumberTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 260));
        setResizable(false);

        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Exit");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jResponseLabel.setText("Employee added!");

        buttonGroup1.add(jFTERadioButton);
        jFTERadioButton.setText("Full time");
        jFTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedFTERadioButton(evt);
            }
        });

        buttonGroup1.add(jPTERadioButton);
        jPTERadioButton.setText("Part time");
        jPTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedPTERadioButton(evt);
            }
        });

        jSalaryLabel.setText("Salary");
        jSalaryLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jSalaryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSalaryTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jFTEPanelLayout = new javax.swing.GroupLayout(jFTEPanel);
        jFTEPanel.setLayout(jFTEPanelLayout);
        jFTEPanelLayout.setHorizontalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFTEPanelLayout.createSequentialGroup()
                .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFTEPanelLayout.setVerticalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jHourlyWageLabel.setText("Hourly Wage");
        jHourlyWageLabel.setMaximumSize(new java.awt.Dimension(57, 16));
        jHourlyWageLabel.setMinimumSize(new java.awt.Dimension(57, 16));

        jHoursPerWeekLabel.setText("Hours per week");
        jHoursPerWeekLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jWeeksPerYearLabel.setText("Weeks per year");
        jWeeksPerYearLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        javax.swing.GroupLayout jPTEPanelLayout = new javax.swing.GroupLayout(jPTEPanel);
        jPTEPanel.setLayout(jPTEPanelLayout);
        jPTEPanelLayout.setHorizontalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jWeeksPerYearTextField))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPTEPanelLayout.setVerticalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jEmployeeNumberLabel.setText("Employee Number");
        jEmployeeNumberLabel.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        jEmployeeNumberLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jFirstNameLabel.setText("First Name");
        jFirstNameLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jFirstNameTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        jFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNameTextFieldActionPerformed(evt);
            }
        });

        jLastNameLabel.setText("Last Name");
        jLastNameLabel.setPreferredSize(new java.awt.Dimension(69, 16));

        jLastNameTextField.setMinimumSize(new java.awt.Dimension(60, 20));

        try {
            javax.swing.text.MaskFormatter formatter = new javax.swing.text.MaskFormatter("*********");
            formatter.setPlaceholderCharacter(' ');
            formatter.setValidCharacters("1234567890 ");
            jEmployeeNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFirstNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLastNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmployeeNumberTextField))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFTERadioButton)
                                .addComponent(jPTERadioButton)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jAddButton)
                            .addGap(41, 41, 41)
                            .addComponent(jRemoveButton)
                            .addGap(38, 38, 38)
                            .addComponent(jResponseLabel))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTERadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPTERadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jRemoveButton)
                    .addComponent(jResponseLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        if (jFTERadioButton.isSelected()) {
            System.out.println(String.join("", getField(FTEFieldArray)));
            employeeTable.add(new FTE(getField(FTEFieldArray)));
            clearField(FTEFieldArray);
        }
        else {
            employeeTable.add(new PTE(getField(PTEFieldArray)));
            clearField(PTEFieldArray);  
        }     
        jResponseLabel.setVisible(true); 
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
          this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void clickedFTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedFTERadioButton
        jPTEPanel.setVisible(false);
        jFTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedFTERadioButton

    private void clickedPTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedPTERadioButton
        jFTEPanel.setVisible(false);
        jPTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedPTERadioButton

    private void jFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNameTextFieldActionPerformed

    private void jSalaryTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSalaryTextFieldKeyPressed
        jSalaryTextField.setText(jSalaryTextField.getText().substring(0, Math.min(jSalaryTextField.getText().length(), 9)));
    }//GEN-LAST:event_jSalaryTextFieldKeyPressed
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddButton;
    private javax.swing.JLabel jEmployeeNumberLabel;
    private javax.swing.JFormattedTextField jEmployeeNumberTextField;
    private javax.swing.JPanel jFTEPanel;
    private javax.swing.JRadioButton jFTERadioButton;
    private javax.swing.JLabel jFirstNameLabel;
    private javax.swing.JTextField jFirstNameTextField;
    private javax.swing.JLabel jHourlyWageLabel;
    private javax.swing.JTextField jHourlyWageTextField;
    private javax.swing.JLabel jHoursPerWeekLabel;
    private javax.swing.JTextField jHoursPerWeekTextField;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JTextField jLastNameTextField;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jPTEPanel;
    private javax.swing.JRadioButton jPTERadioButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JLabel jResponseLabel;
    private javax.swing.JLabel jSalaryLabel;
    private javax.swing.JFormattedTextField jSalaryTextField;
    private javax.swing.JLabel jWeeksPerYearLabel;
    private javax.swing.JTextField jWeeksPerYearTextField;
    // End of variables declaration//GEN-END:variables
}
