import javax.swing.JTextField;

public class AddNewEmployee_jFrame extends javax.swing.JFrame {
    
    public MyHashTable employeeTable;  // This contains the ref value for theHT of MainJFrame.
    public javax.swing.JTextField[] FTEFieldArray;
    public javax.swing.JTextField[] PTEFieldArray;

    public AddNewEmployee_jFrame(MyHashTable employeeTable) {
        initComponents();
        this.employeeTable = employeeTable;
        this.FTEFieldArray = new JTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jSalaryTextField};
        this.PTEFieldArray = new JTextField[]{jEmployeeNumberTextField, jFirstNameTextField, jLastNameTextField, jHourlyWageTextField, jHoursPerWeekTextField, jWeeksPerYearTextField};
        clearField(FTEFieldArray);
        clearField(PTEFieldArray);
        jResponseLabel.setVisible(false); // Hide the Added new employee message
        jFTERadioButton.doClick();   
        pack();
    }
    
    public void clearField(javax.swing.JTextField[] array){
        for (javax.swing.JTextField textField: array){
            textField.setText("");
        }
    }
    
    public String[] getField(javax.swing.JTextField[] array){
        String[] output = new String[array.length];
        for (int i = 0; i < array.length; i++){
            output[i] = array[i].getText();
        }
        return output;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jEmployeeNumberLabel = new javax.swing.JLabel();
        jEmployeeNumberTextField = new javax.swing.JTextField();
        jFirstNameLabel = new javax.swing.JLabel();
        jFirstNameTextField = new javax.swing.JTextField();
        jLastNameLabel = new javax.swing.JLabel();
        jLastNameTextField = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();
        jResponseLabel = new javax.swing.JLabel();
        jFTERadioButton = new javax.swing.JRadioButton();
        jPTERadioButton = new javax.swing.JRadioButton();
        jFTEPanel = new javax.swing.JPanel();
        jSalaryLabel = new javax.swing.JLabel();
        jSalaryTextField = new javax.swing.JTextField();
        jPTEPanel = new javax.swing.JPanel();
        jHourlyWageLabel = new javax.swing.JLabel();
        jHourlyWageTextField = new javax.swing.JTextField();
        jHoursPerWeekLabel = new javax.swing.JLabel();
        jHoursPerWeekTextField = new javax.swing.JTextField();
        jWeeksPerYearLabel = new javax.swing.JLabel();
        jWeeksPerYearTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 260));
        setResizable(false);

        jEmployeeNumberLabel.setText("Employee Number");
        jEmployeeNumberLabel.setToolTipText("Enter a six digit employee number (e.g. 123456)");

        jEmployeeNumberTextField.setToolTipText("");
        jEmployeeNumberTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        jEmployeeNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeNumberTextFieldActionPerformed(evt);
            }
        });

        jFirstNameLabel.setText("First Name");

        jFirstNameTextField.setMinimumSize(new java.awt.Dimension(60, 20));

        jLastNameLabel.setText("Last Name");

        jLastNameTextField.setMinimumSize(new java.awt.Dimension(60, 20));

        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Exit");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jResponseLabel.setText("Employee added!");

        buttonGroup1.add(jFTERadioButton);
        jFTERadioButton.setText("Full time");
        jFTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedFTERadioButton(evt);
            }
        });

        buttonGroup1.add(jPTERadioButton);
        jPTERadioButton.setText("Part time");
        jPTERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedPTERadioButton(evt);
            }
        });

        jSalaryLabel.setText("Salary");

        jSalaryTextField.setToolTipText("");

        javax.swing.GroupLayout jFTEPanelLayout = new javax.swing.GroupLayout(jFTEPanel);
        jFTEPanel.setLayout(jFTEPanelLayout);
        jFTEPanelLayout.setHorizontalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFTEPanelLayout.createSequentialGroup()
                .addComponent(jSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jFTEPanelLayout.setVerticalGroup(
            jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jFTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalaryLabel)
                    .addComponent(jSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        jHourlyWageLabel.setText("Hourly Wage");
        jHourlyWageLabel.setMaximumSize(new java.awt.Dimension(57, 16));
        jHourlyWageLabel.setMinimumSize(new java.awt.Dimension(57, 16));

        jHoursPerWeekLabel.setText("Hours per week");

        jWeeksPerYearLabel.setText("Weeks per year");

        javax.swing.GroupLayout jPTEPanelLayout = new javax.swing.GroupLayout(jPTEPanel);
        jPTEPanel.setLayout(jPTEPanelLayout);
        jPTEPanelLayout.setHorizontalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jHoursPerWeekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jWeeksPerYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jWeeksPerYearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(126, 126, 126))
        );
        jPTEPanelLayout.setVerticalGroup(
            jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTEPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHourlyWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoursPerWeekLabel)
                    .addComponent(jHoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeeksPerYearLabel)
                    .addComponent(jWeeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jEmployeeNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFirstNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLastNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmployeeNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTERadioButton)
                            .addComponent(jPTERadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddButton)
                        .addGap(41, 41, 41)
                        .addComponent(jRemoveButton)
                        .addGap(38, 38, 38)
                        .addComponent(jResponseLabel))
                    .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployeeNumberLabel)
                    .addComponent(jEmployeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTERadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFirstNameLabel)
                    .addComponent(jPTERadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jRemoveButton)
                    .addComponent(jResponseLabel))
                .addContainerGap())
        );

        jEmployeeNumberTextField.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        if (jFTERadioButton.isSelected()) {
            employeeTable.add(new FTE(getField(FTEFieldArray)));
            clearField(FTEFieldArray);
        }
        else {
            employeeTable.add(new PTE(getField(PTEFieldArray)));
            clearField(PTEFieldArray);  
        }     
        jResponseLabel.setVisible(true); 
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
          this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void clickedFTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedFTERadioButton
        jPTEPanel.setVisible(false);
        jFTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedFTERadioButton

    private void clickedPTERadioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedPTERadioButton
        jFTEPanel.setVisible(false);
        jPTEPanel.setVisible(true);
    }//GEN-LAST:event_clickedPTERadioButton

    private void jEmployeeNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeNumberTextFieldActionPerformed
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddButton;
    private javax.swing.JLabel jEmployeeNumberLabel;
    private javax.swing.JTextField jEmployeeNumberTextField;
    private javax.swing.JPanel jFTEPanel;
    private javax.swing.JRadioButton jFTERadioButton;
    private javax.swing.JLabel jFirstNameLabel;
    private javax.swing.JTextField jFirstNameTextField;
    private javax.swing.JLabel jHourlyWageLabel;
    private javax.swing.JTextField jHourlyWageTextField;
    private javax.swing.JLabel jHoursPerWeekLabel;
    private javax.swing.JTextField jHoursPerWeekTextField;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JTextField jLastNameTextField;
    private javax.swing.JPanel jPTEPanel;
    private javax.swing.JRadioButton jPTERadioButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JLabel jResponseLabel;
    private javax.swing.JLabel jSalaryLabel;
    private javax.swing.JTextField jSalaryTextField;
    private javax.swing.JLabel jWeeksPerYearLabel;
    private javax.swing.JTextField jWeeksPerYearTextField;
    // End of variables declaration//GEN-END:variables
}
